[package]
name = "local_history_ui"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
anyhow.workspace = true
chrono.workspace = true
futures.workspace = true
gpui.workspace = true
log.workspace = true

collections.workspace = true
local_history.workspace = true
ui.workspace = true
