[package]
name = "diffsplit"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "diffsplit"
path = "src/main.rs"

[dependencies]
ab_glyph = "0.2"
anyhow = "1.0"
diff = "0.1"
dissimilar = "1.0"
git2 = "0.18"
imara-diff = "0.2"
pixels = "0.15"
regex = "1.0"
similar = "2.6"
winit = "0.29"
gpui = "0.1.0"
